### ISSUE TITLE
[FEAT] 편지함 조회 API

### ISSUE THREAD

**Issue by nicehcy2** [Nior-Near/BE#4]
## Description 
편지함 조회 API

## TODO 
- [x] 편지함 DB 수정
- [x] 편지함 API 명세 수정 
- [x] 편지함 전체 조회
- [ ] 편지합 개별 조회
